// import '@fortawesome/fontawesome-svg-core/style.scss';
// import { config } from '@fortawesome/fontawesome-svg-core';
// config.autoAddCss = false;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
